services:
  memory_whole:
    build: .
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "4747:4747"
    volumes:
      - mw_output:/app/output
    restart: unless-stopped
    environment:
      - PORT=4747
      - FORCE_REGEN=0

volumes:
  mw_output:
    name: mw_output
